apiVersion: v1
kind: Service
metadata:
  name: grafana-ext
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: grafana
# kubectl expose service grafana --type=NodePort --target-port=3000 --name=grafana-ext
