apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-port-forward
  # annotations:
  #   kubectl.kubernetes.io/last-applied-configuration: ""
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30900
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
# kubectl expose deployment prometheus-server --type=NodePort --target-port=9090 --port=9090
