apiVersion: v1
kind: Service
metadata:
  name: prometheus-server-ext
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30900
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus
# kubectl expose service prometheus-server --type=NodePort --target-port=9090 --name=prometheus-server-ext
