apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
type: kubernetes.io/basic-auth
stringData:
  username: sachin
  password: sachin123
  url: jdbc:mysql://mysql:3306/lentra?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&autoReconnect=true
