apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: lentra-app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lentra-app-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 10
